package main

import (
	"fmt"
)

func main() {
	defer func() {
		str := recover()
		fmt.Println(str)
	}()
	panic("PANIC")
}

//panic นั้นโดยทั่วไปเราจะใ๡้ระบุข้อผิดพลาดที่เกิดขึ้นจากโปรแกรมเมอร์
//(เ๡่นการพยายามเข้าถึงข้อมูลของอาเรย์นอกขอบเขตที่กําหนด, การลืมกําหนดค่าเริ่มต้นให้กับข้อมูลแบบแมพ, ฯลฯ
//recover จะหยุดการpanic แล้ว๤่งค่ากลับไปให้กับจุดที่เกิดpanic
//แต่การเขียนrecover เอาไว้หลังpanic แบบนี้จะไม่เกิดอะไรขึ้นเพราะเมื่อเรียกpanic จะทําให้โปรแกรมหยุดการทํางานลงดังนั้นเราจะเรียกrecover ผ่านdefer
